version: "3.1"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - api_data:/var/lib/postgresql/data
      - ./psql_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
  api:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/home/node/app
    ports:
      - "8080:8080"
    links:
      - db:database
    command: "node server.js"

volumes:
  api_data: